var searchData=
[
  ['k_5fcasinh_2ec',['k_casinh.c',['../k__casinh_8c.html',1,'']]],
  ['k_5fcasinhf_2ec',['k_casinhf.c',['../k__casinhf_8c.html',1,'']]],
  ['k_5fcasinhl_2ec',['k_casinhl.c',['../k__casinhl_8c.html',1,'']]],
  ['k_5fcos_2ec',['k_cos.c',['../k__cos_8c.html',1,'']]],
  ['k_5fcosf_2ec',['k_cosf.c',['../ieee754_2flt-32_2k__cosf_8c.html',1,'(Global Namespace)'],['../powerpc_2fpu_2k__cosf_8c.html',1,'(Global Namespace)']]],
  ['k_5fcosl_2ec',['k_cosl.c',['../math_2k__cosl_8c.html',1,'(Global Namespace)'],['../sysdeps_2ieee754_2ldbl-128_2k__cosl_8c.html',1,'(Global Namespace)'],['../sysdeps_2ieee754_2ldbl-128ibm_2k__cosl_8c.html',1,'(Global Namespace)'],['../sysdeps_2ieee754_2ldbl-96_2k__cosl_8c.html',1,'(Global Namespace)'],['../sysdeps_2m68k_2m680x0_2fpu_2k__cosl_8c.html',1,'(Global Namespace)']]],
  ['k_5frem_5fpio2_2ec',['k_rem_pio2.c',['../ia64_2fpu_2k__rem__pio2_8c.html',1,'(Global Namespace)'],['../ieee754_2dbl-64_2k__rem__pio2_8c.html',1,'(Global Namespace)'],['../m68k_2m680x0_2fpu_2k__rem__pio2_8c.html',1,'(Global Namespace)']]],
  ['k_5frem_5fpio2f_2ec',['k_rem_pio2f.c',['../ia64_2fpu_2k__rem__pio2f_8c.html',1,'(Global Namespace)'],['../ieee754_2flt-32_2k__rem__pio2f_8c.html',1,'(Global Namespace)'],['../m68k_2m680x0_2fpu_2k__rem__pio2f_8c.html',1,'(Global Namespace)'],['../powerpc_2fpu_2k__rem__pio2f_8c.html',1,'(Global Namespace)']]],
  ['k_5frem_5fpio2l_2ec',['k_rem_pio2l.c',['../math_2k__rem__pio2l_8c.html',1,'(Global Namespace)'],['../sysdeps_2i386_2fpu_2k__rem__pio2l_8c.html',1,'(Global Namespace)'],['../sysdeps_2ia64_2fpu_2k__rem__pio2l_8c.html',1,'(Global Namespace)'],['../sysdeps_2m68k_2m680x0_2fpu_2k__rem__pio2l_8c.html',1,'(Global Namespace)'],['../sysdeps_2x86__64_2fpu_2k__rem__pio2l_8c.html',1,'(Global Namespace)']]],
  ['k_5fsin_2ec',['k_sin.c',['../k__sin_8c.html',1,'']]],
  ['k_5fsincosl_2ec',['k_sincosl.c',['../math_2k__sincosl_8c.html',1,'(Global Namespace)'],['../sysdeps_2ieee754_2ldbl-128_2k__sincosl_8c.html',1,'(Global Namespace)'],['../sysdeps_2ieee754_2ldbl-128ibm_2k__sincosl_8c.html',1,'(Global Namespace)']]],
  ['k_5fsinf_2ec',['k_sinf.c',['../ieee754_2flt-32_2k__sinf_8c.html',1,'(Global Namespace)'],['../powerpc_2fpu_2k__sinf_8c.html',1,'(Global Namespace)']]],
  ['k_5fsinl_2ec',['k_sinl.c',['../math_2k__sinl_8c.html',1,'(Global Namespace)'],['../sysdeps_2ieee754_2ldbl-128_2k__sinl_8c.html',1,'(Global Namespace)'],['../sysdeps_2ieee754_2ldbl-128ibm_2k__sinl_8c.html',1,'(Global Namespace)'],['../sysdeps_2ieee754_2ldbl-96_2k__sinl_8c.html',1,'(Global Namespace)'],['../sysdeps_2m68k_2m680x0_2fpu_2k__sinl_8c.html',1,'(Global Namespace)']]],
  ['k_5fstandard_2ec',['k_standard.c',['../k__standard_8c.html',1,'']]],
  ['k_5fstandardf_2ec',['k_standardf.c',['../k__standardf_8c.html',1,'']]],
  ['k_5fstandardl_2ec',['k_standardl.c',['../k__standardl_8c.html',1,'']]],
  ['k_5ftan_2ec',['k_tan.c',['../k__tan_8c.html',1,'']]],
  ['k_5ftanf_2ec',['k_tanf.c',['../ieee754_2flt-32_2k__tanf_8c.html',1,'(Global Namespace)'],['../m68k_2m680x0_2fpu_2k__tanf_8c.html',1,'(Global Namespace)']]],
  ['k_5ftanl_2ec',['k_tanl.c',['../math_2k__tanl_8c.html',1,'(Global Namespace)'],['../sysdeps_2ieee754_2ldbl-128_2k__tanl_8c.html',1,'(Global Namespace)'],['../sysdeps_2ieee754_2ldbl-128ibm_2k__tanl_8c.html',1,'(Global Namespace)'],['../sysdeps_2ieee754_2ldbl-96_2k__tanl_8c.html',1,'(Global Namespace)'],['../sysdeps_2m68k_2m680x0_2fpu_2k__tanl_8c.html',1,'(Global Namespace)']]],
  ['kd_2eh',['kd.h',['../kd_8h.html',1,'']]],
  ['kernel_2dfeatures_2eh',['kernel-features.h',['../mach_2hurd_2kernel-features_8h.html',1,'(Global Namespace)'],['../nacl_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2alpha_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2arm_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2hppa_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2i386_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2ia64_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2m68k_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2microblaze_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2mips_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2powerpc_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2s390_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2sh_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2sparc_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2tile_2kernel-features_8h.html',1,'(Global Namespace)'],['../unix_2sysv_2linux_2x86__64_2kernel-features_8h.html',1,'(Global Namespace)']]],
  ['kernel_2dposix_2dcpu_2dtimers_2eh',['kernel-posix-cpu-timers.h',['../kernel-posix-cpu-timers_8h.html',1,'']]],
  ['kernel_2dposix_2dtimers_2eh',['kernel-posix-timers.h',['../kernel-posix-timers_8h.html',1,'']]],
  ['kernel_5frt_5fsigframe_2eh',['kernel_rt_sigframe.h',['../aarch64_2kernel__rt__sigframe_8h.html',1,'(Global Namespace)'],['../mips_2kernel__rt__sigframe_8h.html',1,'(Global Namespace)'],['../nios2_2kernel__rt__sigframe_8h.html',1,'(Global Namespace)']]],
  ['kernel_5fsigaction_2eh',['kernel_sigaction.h',['../alpha_2kernel__sigaction_8h.html',1,'(Global Namespace)'],['../hppa_2kernel__sigaction_8h.html',1,'(Global Namespace)'],['../kernel__sigaction_8h.html',1,'(Global Namespace)'],['../mips_2kernel__sigaction_8h.html',1,'(Global Namespace)']]],
  ['kernel_5fstat_2eh',['kernel_stat.h',['../alpha_2kernel__stat_8h.html',1,'(Global Namespace)'],['../generic_2kernel__stat_8h.html',1,'(Global Namespace)'],['../hppa_2kernel__stat_8h.html',1,'(Global Namespace)'],['../ia64_2kernel__stat_8h.html',1,'(Global Namespace)'],['../kernel__stat_8h.html',1,'(Global Namespace)'],['../microblaze_2kernel__stat_8h.html',1,'(Global Namespace)'],['../mips_2kernel__stat_8h.html',1,'(Global Namespace)'],['../powerpc_2powerpc32_2kernel__stat_8h.html',1,'(Global Namespace)'],['../powerpc_2powerpc64_2kernel__stat_8h.html',1,'(Global Namespace)'],['../s390_2s390-64_2kernel__stat_8h.html',1,'(Global Namespace)'],['../sparc_2sparc32_2kernel__stat_8h.html',1,'(Global Namespace)'],['../sparc_2sparc64_2kernel__stat_8h.html',1,'(Global Namespace)'],['../x86__64_2kernel__stat_8h.html',1,'(Global Namespace)']]],
  ['kernel_5fsysinfo_2eh',['kernel_sysinfo.h',['../kernel__sysinfo_8h.html',1,'']]],
  ['kernel_5ftermios_2eh',['kernel_termios.h',['../alpha_2kernel__termios_8h.html',1,'(Global Namespace)'],['../kernel__termios_8h.html',1,'(Global Namespace)'],['../mips_2kernel__termios_8h.html',1,'(Global Namespace)'],['../powerpc_2kernel__termios_8h.html',1,'(Global Namespace)'],['../sparc_2kernel__termios_8h.html',1,'(Global Namespace)']]],
  ['key_2dlookup_2ec',['key-lookup.c',['../key-lookup_8c.html',1,'']]],
  ['key_5fcall_2ec',['key_call.c',['../key__call_8c.html',1,'']]],
  ['key_5fprot_2ec',['key_prot.c',['../key__prot_8c.html',1,'']]],
  ['key_5fprot_2eh',['key_prot.h',['../include_2rpc_2key__prot_8h.html',1,'(Global Namespace)'],['../sunrpc_2rpc_2key__prot_8h.html',1,'(Global Namespace)']]],
  ['kill_2ec',['kill.c',['../signal_2kill_8c.html',1,'(Global Namespace)'],['../sysdeps_2mach_2hurd_2kill_8c.html',1,'(Global Namespace)']]],
  ['killpg_2ec',['killpg.c',['../signal_2killpg_8c.html',1,'(Global Namespace)'],['../sysdeps_2posix_2killpg_8c.html',1,'(Global Namespace)']]],
  ['klog_2eh',['klog.h',['../klog_8h.html',1,'']]],
  ['koi_2d8_2ec',['koi-8.c',['../koi-8_8c.html',1,'']]],
  ['koi8_2dr_2ec',['koi8-r.c',['../koi8-r_8c.html',1,'']]],
  ['koi8_2dru_2ec',['koi8-ru.c',['../koi8-ru_8c.html',1,'']]],
  ['koi8_2dt_2ec',['koi8-t.c',['../koi8-t_8c.html',1,'']]],
  ['koi8_2du_2ec',['koi8-u.c',['../koi8-u_8c.html',1,'']]],
  ['ksc5601_2ec',['ksc5601.c',['../ksc5601_8c.html',1,'']]],
  ['ksc5601_2eh',['ksc5601.h',['../ksc5601_8h.html',1,'']]]
];
